from setuptools import setup, find_packages

setup(
    name="alcos",
    version="1.0.0",
    description="Agentic Local Core OS - Elite local autonomous AI system",
    author="Autonomous Systems Team",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "fastapi==0.104.1",
        "uvicorn==0.24.0",
        "websockets==12.0",
        "pydantic==2.5.0",
        "pydantic-settings==2.1.0",
        "python-dotenv==1.0.0",
        "aiofiles==23.2.1",
        "requests==2.31.0",
        "httpx==0.25.0",
        "chromadb==0.4.10",
        "sentence-transformers==2.2.2",
        "numpy==1.24.3",
        "torch==2.0.1",
        "ollama==0.0.36",
        "litellm==1.3.0",
        "langchain==0.1.0",
        "langgraph==0.0.32",
        "docker==7.0.0",
        "psutil==5.9.6",
        "pyyaml==6.0.1",
        "click==8.1.7",
        "rich==13.7.0",
        "colorama==0.4.6",
        "loguru==0.7.2",
        "SQLAlchemy==2.0.23",
        "alembic==1.13.0",
    ],
    extras_require={
        "dev": [
            "pytest==7.4.3",
            "pytest-asyncio==0.21.1",
            "pytest-cov==4.1.0",
            "black==23.12.0",
            "flake8==6.1.0",
            "mypy==1.7.1",
            "isort==5.13.2",
        ],
        "gpu": [
            "cuda-toolkit>=11.8",
            "onnxruntime-gpu>=1.16.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "agentic-core-os=alcos.cli:main",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
